name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Log versions
        run: |
          node -v
          yarn --version
          git --version

      - name: Log GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Log yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Packages
        run: yarn install

      - name: Run Linter Prettier
        run: ./node_modules/.bin/prettier --write "**/*.*"   

      - name: Run Linter ESLint
        run: ./node_modules/.bin/eslint --fix "**/*.*"

      - name: Log Git Status
        run: git status

      - name: Run Jest UNIT Tests
        run: yarn test:unitCI

      - name: Build App
        run: yarn build

      - name: Serve App
        run: yarn start

      - name: Run Puppeteer E2E Tests
        uses: ianwalter/puppeteer@master
        with:
          args: yarn test

      - name: Commit and Push Changes
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Updating Domain
        run: echo "Update domain"
