name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Log versions
        run: |
          node -v
          yarn --version
          git --version

      - name: Log GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Install Packages
        run: yarn install 

      - name: Run Linter ESLint
        run: ./node_modules/.bin/eslint --fix "**/*.*"

      - name: Run Linter Prettier
        run: ./node_modules/.bin/prettier --write --config ./.prettierrc "**/*.*"  

      - name: Commit Lint Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "CI Lint Action"
          git add --all
          git diff-index --quiet HEAD || git commit -m "(CI)Lint: ${{github.event.commits[0].message}}"

      - name: Run Jest UNIT Tests
        run: yarn test-ci:unit

      - name: Upload test coverage as artifact
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage

      - name: Build App
        run: yarn build

      - name: Host App locally
        run: yarn start & (sleep 30 && exit)
        #TODO use build instead of devbuilding again
        #run: ./node_modules/.bin/serve -s build -l 3000 & (sleep 30 && exit)

      - name: Setup Files for Puppeteer
        run: |
          sed -i '' 's/headless: false/headless: true/g' features/support/scope/BrowserScope.js

      - name: Run Puppeteer E2E Tests
        run: yarn test-ci:e2e

      - name: Setup Files for Commit
        run: |
          sed -i '' 's/headless: true/headless: false/g' features/support/scope/BrowserScope.js

      - name: Commit Test Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "CI Test Action"
          git add --all
          git diff-index --quiet HEAD || git commit -m "(CI)Test: ${{github.event.commits[0].message}}"

      - name: Release 
        run: yarn release

      - name: Commit Changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "CI Release Action"
          git add --all
          git diff-index --quiet HEAD || git commit -m "(CI)Release: ${{github.event.commits[0].message}}"

      - name: Push changes to master
        run: git push "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git" HEAD:master
          
      - name: Push copy to stable
        run: git push "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git" HEAD:stable

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Updating Domain
        run: echo "Update domain"
